"""Phase 4: turn a clause + its risk label + retrieved statute evidence into a
trustworthy, grounded explanation.

The LLM is asked for STRUCTURED output, not free prose, specifically so the grounding
guardrail (app.explain.grounding) can check it mechanically rather than by re-reading
generated English:

  - `document_says`: a faithful restatement of the clause itself - required to closely
    track the actual clause text, checked by the guardrail's token-overlap test.
  - `concern`: why this might matter to a tenant, in hedged, non-conclusory language.
  - `statute_support`: a list of {entry_id, how_it_applies}, where entry_id MUST be one
    of the ids actually retrieved and passed in this call - the model is shown the exact
    allowed id list and told to leave this empty rather than invent one.

The legal-disclaimer text is never generated by the model - it is fixed, constant text
appended by the pipeline, so its wording can never drift from what the rest of the
product requires on every screen showing AI output.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field

from app.llm_client import LLMClient

DISCLAIMER = (
    "This is AI-assisted information, not legal advice. Laws vary by location and "
    "change over time — verify with a qualified professional before acting."
)

SYSTEM_PROMPT = """You explain residential lease clauses to a tenant using a lease-review
tool. You will be given a clause's text, a risk label already assigned by a separate
classifier (GREEN/YELLOW/RED), and zero or more retrieved statute excerpts that may or
may not be relevant.

Rules, all non-negotiable:
1. Separate two things: what the document literally says, and why that might be a
   concern. Never blend them into one sentence.
2. NEVER state that anything "is illegal", "is void", "is unenforceable", or give any
   other definitive legal conclusion. Use hedged language: "may be", "could be",
   "a court might view this as", "this is the kind of term that sometimes...".
3. You may cite a statute ONLY from the "Retrieved statutes" list you are given, by its
   exact id. If you did not receive any statute, or none of the ones you received
   actually apply, leave statute_support empty — do NOT name any other Act, Section, or
   statute from your own knowledge. Citing anything not in the provided list is a
   critical failure of this task, more serious than saying nothing.
4. If the risk label is YELLOW or RED, you must give a real, specific concern grounded
   in the clause's own text — not a generic warning that could apply to any clause.
5. If the risk label is GREEN, keep "concern" short and say plainly that this is
   standard/balanced language, rather than inventing a concern to sound thorough.

Reply with ONLY a JSON object, no other text, in exactly this shape:
{"document_says": "...", "concern": "...", "statute_support": [{"entry_id": "...", "how_it_applies": "..."}]}
"""


@dataclass
class ExplanationResult:
    clause_id: str
    risk_label: str
    document_says: str
    concern: str
    statute_support: list[dict] = field(default_factory=list)
    disclaimer: str = DISCLAIMER
    raw_reply: str = ""


def _build_prompt(clause_text: str, risk_label: str, retrieved: list[dict]) -> list[dict]:
    if retrieved:
        allowed_ids = ", ".join(r["entry_id"] for r in retrieved)
        statute_block = "\n".join(
            f"- id={r['entry_id']} | {r['citation']}: {r['excerpt_text']}" for r in retrieved
        )
        statute_section = (
            f"Retrieved statutes (you may cite ONLY these ids: {allowed_ids}):\n{statute_block}"
        )
    else:
        statute_section = (
            "Retrieved statutes: none. No statute was retrieved for this clause's "
            "jurisdiction/topic — leave statute_support empty. Do not name any Act or "
            "Section from your own knowledge."
        )

    user_content = (
        f"Clause text:\n{clause_text}\n\n"
        f"Risk label (already assigned, do not re-classify): {risk_label}\n\n"
        f"{statute_section}"
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def parse_reply(content: str, clause_id: str, risk_label: str) -> ExplanationResult:
    match = re.search(r"\{.*\}", content, re.DOTALL)
    if not match:
        raise ValueError(f"no JSON in reply: {content[:150]!r}")
    data = json.loads(match.group(0))
    document_says = str(data.get("document_says", "")).strip()
    concern = str(data.get("concern", "")).strip()
    statute_support = data.get("statute_support") or []
    if not isinstance(statute_support, list):
        raise ValueError(f"statute_support must be a list, got {type(statute_support)}")
    cleaned_support = []
    for item in statute_support:
        if isinstance(item, dict) and item.get("entry_id"):
            cleaned_support.append({
                "entry_id": str(item["entry_id"]),
                "how_it_applies": str(item.get("how_it_applies", "")).strip(),
            })
    if not document_says:
        raise ValueError("document_says was empty")
    return ExplanationResult(
        clause_id=clause_id,
        risk_label=risk_label,
        document_says=document_says,
        concern=concern,
        statute_support=cleaned_support,
        raw_reply=content,
    )


def generate_explanation(
    clause_id: str, clause_text: str, risk_label: str, retrieved: list[dict], *, client: LLMClient | None = None
) -> ExplanationResult:
    """retrieved: the exact list returned by app.statute_kb.retrieval.retrieve_statute()
    for this clause - never a broader set, so the allowed-citation list the model sees
    matches what the grounding guardrail will check against."""
    client = client or LLMClient(max_tokens=1100)
    messages = _build_prompt(clause_text, risk_label, retrieved)
    content = client.chat(messages)
    try:
        return parse_reply(content, clause_id, risk_label)
    except (ValueError, json.JSONDecodeError):
        content = client.chat(messages)  # one retry on a malformed reply
        return parse_reply(content, clause_id, risk_label)
